### ISSUE TITLE
android.content.ActivityNotFoundException:

### ISSUE THREAD

**Issue by savvisingh** [googlesamples/android-dynamic-features#10]
android.content.ActivityNotFoundException: Unable to find explicit activity class {com.myapp.videomodule/com.myapp.videomodule.VideoCallActivity}; have you declared this activity in your AndroidManifest.xml?

My app package is com.myapp.doctors
module package is com.myapp.videomodule

I am still confused how that same thing is working with this project but not with my own project.
My code 
`if(splitInstallManager.getInstalledModules().contains("videomodule")){
Intent intent = new Intent(); 
        intent.setClassName("com.myapp.videomodule","com.myapp.videomodule.VideoCallActivity");
            startActivity(intent);
        }`

**Comment by keyboardsurfer** [comment]
This is out of scope for this sample's issue tracker. Please create a question on StackOverflow.
Feel free to post it as comment here and I'll take a look.

**Comment by dbsheta** [comment]
I am also having the same issue. I tried following AppBundle guide but didn't have any problem. I even tried adding a new dynamic module to this project. Then too getting the same exception

**Comment by keyboardsurfer** [comment]
Is the code open source or can you create a [MVCE](https://stackoverflow.com/help/mcve)?
