### ISSUE TITLE
groovy.lang.MissingPropertyException: Could not set unknown property 'dynamicFeatures' for object of type com.android.build.gradle.AppExtension.

### ISSUE THREAD

**Issue by CJC-ivotten** [googlesamples/android-dynamic-features#15]
I build the project , and Android Studio 3.2 throw this error，
![3a s4v_8 c1 9f w xnmw](https://user-images.githubusercontent.com/13750402/46597900-a6061100-cb14-11e8-94c7-c8abea968393.png)

**Comment by abhishekdewan101** [comment]
I can confirm this is happening to me as well. 

Error reads like 

Could not set unknown property 'dynamicFeatures' for object of type com.android.build.gradle.AppExtension

![screen shot 2018-12-14 at 10 43 40 am](https://user-images.githubusercontent.com/2817833/50021200-27eb3e00-ff8d-11e8-808f-a4b011175bf6.png)

**Comment by infeornnandhu** [comment]
1. Try updating `targetSdkVersion` and `compileSdkVersion`
2. Update Gradle version to latest.
3. If you are using Kotlin, update Kotlin to a newer version


This solved my problem.

**Comment by keyboardsurfer** [comment]
This very much looks like an issue with plugin versioning.
If [this comment](https://github.com/googlesamples/android-dynamic-features/issues/15#issuecomment-464994132) doesn't resolve it, feel free to comment on this issue again.
