### ISSUE TITLE
FAILURE: Build failed with an exception.

### ISSUE THREAD

**Issue by 10045125** [googlesamples/android-dynamic-features#17]
buildTypes {
        debug {}
        release {
            minifyEnabled true
            shrinkResources true
        }
    }

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Resource shrinker cannot be used for multi-apk applications

I need your help，thinks！

**Comment by keyboardsurfer** [comment]
This is not a sample issue but [being tracked](https://issuetracker.google.com/issues/120517460) here.

**Comment by wbervoets** [comment]
Any update when this bug will be fixed?

**Comment by keyboardsurfer** [comment]
This is not an issue in the sample. I recommend starring the [issuetracker issue](https://issuetracker.google.com/issues/120517460).

**Comment by wbervoets** [comment]
@keyboardsurfer I know, but we don't know if the issuetracker will be accepted/fixed in the future and when in the case it is accepted. (at least we receive some feedback here ;-))

**Comment by 10045125** [comment]
Mark, thinks!

**Comment by pfmaggi** [comment]
This request is currently tracked on the public issuetracker:
[Unable to use `shrinkResources` in base module with dynamic features](https://issuetracker.google.com/120517460)

You can follow there the updates.
