### ISSUE TITLE
Dynamic feature Module error code -2

### ISSUE THREAD

**Issue by manishkummar21** [googlesamples/android-dynamic-features#22]
Hi

I Created dynamic feature module and followed steps everything accordingly in documents

Now i want to test the dynamic module is working or not

Note : - dynamic feature directly installing  from android studio

so i builded the apks from bundletool and installed to connected device when its trying to download the module i am getting exceptions as code -2 which is module is unavailable and so same thing tried by uploading bundle in internal test track i am facing same error. Please anyone help on this.

**Comment by manishkummar21** [comment]
I got it thanks for reply

**Comment by chainchelliah** [comment]
Hi @manishkummar21 ,

I'm also stuck with this issue. Please help me how did you fix this issue?

**Comment by keyboardsurfer** [comment]
If the apk are not installed through the Play Store they won't install. You'll have to install either all required apk directly or upload to the internal testing track and download from there.

**Comment by manishkummar21** [comment]
Hi @chainchelliah please change the deploy options from default apk to aab bundle in edit configuration before building application.

**Comment by DurgaArunkumarSmitiv** [comment]
Facing same issue when importing this project.  Why it is returning -2error. I tried deploying through bundletool as well as Android studio >edit configuration>Apk and Andoroid Bundle. But when I run always it is returning -2 error in onfailurelistener.

**Comment by dbof10** [comment]
same issue. not sure what go wrong

**Comment by chathura2020** [comment]
@keyboardsurfer can this be a result of having an out of date google play service on the device? so play core library will not download the necessary modules even though they are available as a dynamic feature modules. Therefore it shows module unavailable error.

**Comment by alexhorsa** [comment]
@chathura2020 I had this message "ZIP End of Central Directory record not found" with error code -11 [SPLITCOMPAT_VERIFICATION_ERROR](https://developer.android.com/reference/com/google/android/play/core/splitinstall/model/SplitInstallErrorCode.html#splitcompat_verification_error) and updating Google Play Store app solved it
