### ISSUE TITLE
When the google play start download demand modules when I use deferredInstall

### ISSUE THREAD

**Issue by xsbupt** [googlesamples/android-dynamic-features#23]
When I use deferredInstall, I do not know when the google play start to download the demand modules,  I put my application to background, still not download

**Comment by pfmaggi** [comment]
I'm closing this issue because, as reported in the [documentation](https://developer.android.com/guide/app-bundle/playcore#deferred_install), this is the expected behavior:

> *Requests for deferred installs are best-effort and you cannot track their progress.*
