### ISSUE TITLE
Build Failed in dynamic feature when using multiple product flavors in base module

### ISSUE THREAD

**Issue by sailesh2** [googlesamples/android-dynamic-features#25]
In my Dynamic feature module build.gradle, it adds dependency to my main base module, and it works fine if i don't have product flavors in my base module. But build fails with following exception when i add multiple product flavors in my base module

FAILURE: Build failed with an exception.

> What went wrong:
Could not determine the dependencies of task ':dynamicimage:externalNativeBuildDebug'.
> Could not resolve all files for configuration ':dynamicimage:debugRuntimeClasspath'.
   > Could not resolve project :app.
     Required by:
         project :dynamicimage
      > Cannot choose between the following configurations of project :app:
          - alphaDebugRuntimeElements
          - betaDebugRuntimeElements
        All of them match the consumer attributes:
          - Configuration 'alphaDebugRuntimeElements':
              - Required com.android.build.api.attributes.BuildTypeAttr 'debug' and found compatible value 'debug'.
              - Found com.android.build.api.attributes.VariantAttr 'alphaDebug' but wasn't required.
              - Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Apk' and found compatible value 'Apk'.
              - Required org.gradle.usage 'java-runtime' and found compatible value 'java-runtime'.
              - Found version 'alpha' but wasn't required.
          - Configuration 'betaDebugRuntimeElements':
              - Required com.android.build.api.attributes.BuildTypeAttr 'debug' and found compatible value 'debug'.
              - Found com.android.build.api.attributes.VariantAttr 'betaDebug' but wasn't required.
              - Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Apk' and found compatible value 'Apk'.
              - Required org.gradle.usage 'java-runtime' and found compatible value 'java-runtime'.
              - Found version 'beta' but wasn't required.

**Comment by sailesh2** [comment]
This issue got fixed after adding same product flavors (with no configuration) in my Dynamic Feature 
 module build.gradle. A similar issue is mentioned in [https://github.com/googlesamples/android-instant-apps/issues/13 ](url) 

However is there better way to fix this instead of adding empty product flavors  in all Dynamic Feature module build.gradle ?

**Comment by keyboardsurfer** [comment]
That's what [missingDimensionStrategy](https://google.github.io/android-gradle-dsl/current/com.android.build.gradle.internal.dsl.DefaultConfig.html#com.android.build.gradle.internal.dsl.DefaultConfig:missingDimensionStrategy(java.lang.String,%20java.lang.String)) is there for.
