### ISSUE TITLE
Accessing only Layout from Dynamic feature.

### ISSUE THREAD

**Issue by saketkumar** [googlesamples/android-dynamic-features#27]
I'm using Dynamic Feature in my app and I have one layout in my dynamic feature. Without creating the activity I want to access the layout directly in my base app and whenever the dynamic feature is installed then the layout from dynamic feature will be displayed. If not installed , I'm just showing my layout which is in base app.

@keyboardsurfer Can you please help me in this and let me know how to access the layout from dynamic to base.

**Comment by keyboardsurfer** [comment]
This is a question that's out of scope for the sample we're looking at.
Please create a question on StackOverflow, providing some more info on this.

**Comment by saketkumar** [comment]
@keyboardsurfer https://stackoverflow.com/questions/54322435/using-dynamic-app-feature-in-base-application Please check.
