### ISSUE TITLE
SplitInstallManager.startInstall Handling offline case (error -6)

### ISSUE THREAD

**Issue by chronvas** [googlesamples/android-dynamic-features#29]
In a case that a device is offline, the progressbar is showing at a constant 0%.
If add a failure listener at that point, an error comes back with code -6

Should it be handled in this code lab?

**Comment by pfmaggi** [comment]
Thanks for opening this issue.

The idea with this sample is to showcase the API in the simplest way and we would like to avoid to add any additional code to check for connectivity.

If you're looking for a more complex sample showcasing how to handle missing connectivity (or being on a metered connection) you can take a look at 2018 Santa Tracker project.

[This article describe the approach used in that application](https://medium.com/androiddevelopers/google-santa-tracker-moving-to-an-android-app-bundle-dde180716096).
