### ISSUE TITLE
Are there any way to check the dynamic feature download?

### ISSUE THREAD

**Issue by moisesvs** [googlesamples/android-dynamic-features#30]
Hi,

When I tried Android dynamic feature in this moment there had any way for testing the dynamic feature download (without Google Play). Right now, Are there any way to check this? or the situation is the same...

Thanks a lot

**Comment by pfmaggi** [comment]
Hi and thanks for the question.
At this moment it's only possible to test dynamic features through Google Play. The best option is to use an **Internal Test Track** that, after the initial creation of the track, allows to test your application as soon as you upload it to the Play Console.

We know that this is a highly requested feature and we're looking into possibilities to simplify this process. We're going to make available more information as soon as they're available.
