### ISSUE TITLE
Basic Espresso test for feature module

### ISSUE THREAD

**Issue by vahidlazio** [googlesamples/android-dynamic-features#32]
That would be really amazing if we could have a really basic espresso test for the DFM to check the basic configurations & dependencies like multidex and etc. 

Currently the activity that on which, i'm trying to have an UI test can not be found in original dex. not sure if i have to do something special to fix the problem.

**Comment by rosaliagomez** [comment]
https://github.com/googlesamples/android-testing/issues/189

**Comment by keyboardsurfer** [comment]
Fixed in https://github.com/googlesamples/android-dynamic-features/commit/18d32e5b3a89eb459c52ca5555fcdc36c4fbf0af
