### ISSUE TITLE
Downloading via playstore internal track issue

### ISSUE THREAD

**Issue by deejaygeekout** [googlesamples/android-dynamic-features#33]
When I have downloaded the module and launch the activity. The activity has issue and goes back to previous activity.

Uploaded new version then when you update it via playstore, the previous activity that is not launching successfully will now launch.

Why it's not working on first try download via manager?

**Comment by pfmaggi** [comment]
Thanks for reporting this.
Can you please clarify how you've installed the application the first time?

**Comment by deejaygeekout** [comment]
Solved it by having base appcompat with split.install
