### ISSUE TITLE
Dynamic Feature with existing flavor on main APP module

### ISSUE THREAD

**Issue by deejaygeekout** [googlesamples/android-dynamic-features#34]
https://github.com/googlesamples/android-dynamic-features/issues/25

As per this I have added flavor in the dynamic module and configured the folders to adapt in flavors. But this is the next error. I have tried to disable split. but it's not working

Cannot find PROCESSED_RES output for Main{type=MAIN, fullName=phDebug, filters=[], versionCode=1, versionName=1.0}

**Comment by smartfuse** [comment]
I am also getting a 

```
Cannot find PROCESSED_RES output for Main{type=MAIN, fullName=phDebug, filters=[], versionCode=1, versionName=1.0}
```

at the processResources step in Gradle. The "out" folder in the processed resources directory is empty for the feature module's build directory. Is there a fix for this?

**Comment by pfmaggi** [comment]
[Stackoverflow](https://stackoverflow.com/questions/tagged/dynamic-feature) might be a better forum for this kind of questions. This one is for issues with the sample.
