### ISSUE TITLE
dynamic feature resource not found exception

### ISSUE THREAD

**Issue by mohanmanu484** [googlesamples/android-dynamic-features#39]
when onDemand flag is set to true in manifest , I'am getting resource not found exception though I have downloaded complete feature module from playstore. But works fine when onDemand is false. Here is the stack trace

 android.content.res.Resources$NotFoundException: String resource ID #0x7e060009
        at android.content.res.Resources.getText(Resources.java:348)
        at android.content.res.Resources.getString(Resources.java:441)

**Comment by Baobomb** [comment]
Same issue happened with my application :(
Does anyone know how to fix this issue?

**Comment by TechaosAdam** [comment]
I have been banging away at this issue all day, and I found a hack that works (for now). 

-> make your application id match the package of your main app, that leads to your launch activity:
     -> com.something.main (for your application id)
     -> com.something.main (for your main package)

-> then make your dynamic feature have the same package, with an added package on the end:
    -> com.something.main.dynamic

-> if you leave this as-is, your resources in the dynamic module will not get installed properly with the dynamic delivery.  To fix this, move your dynamic module layout files to your main app layout file.  Then, in your dynamic module fragment/activity, access the R.layout from your main activity.  Import the R file from your main project.  This way, your resource layout, or whatever else is shipped with the main module, and will work properly when the dynamic feature is downloaded.....

If anyone finds the right way to do this, or the bug is fixed and you read this, please email me at techaos@techaos.com and tell me the solution PLEASE.

**Comment by Baobomb** [comment]
> I have been banging away at this issue all day, and I found a hack that works (for now).
> 
> -> make your application id match the package of your main app, that leads to your launch activity:
> -> com.something.main (for your application id)
> -> com.something.main (for your main package)
> 
> -> then make your dynamic feature have the same package, with an added package on the end:
> -> com.something.main.dynamic
> 
> -> if you leave this as-is, your resources in the dynamic module will not get installed properly with the dynamic delivery. To fix this, move your dynamic module layout files to your main app layout file. Then, in your dynamic module fragment/activity, access the R.layout from your main activity. Import the R file from your main project. This way, your resource layout, or whatever else is shipped with the main module, and will work properly when the dynamic feature is downloaded.....
> 
> If anyone finds the right way to do this, or the bug is fixed and you read this, please email me at [techaos@techaos.com](mailto:techaos@techaos.com) and tell me the solution PLEASE.

This will work because the Resource file already been included with main package.
But by this way, it not what we want dynamic feature do...(Separate the res and class what user doesn't need at first...)

Hope some one can find the way to access res file in dynamic module :(

**Comment by Stjinchan** [comment]
@mohanmanu484 Are you using fragments by any chance?
I have a dynamic module containing layout, strings and a kotlin file. Installing the module works fine, however when trying to load that fragment I get an NotFoundException on my fragment layout.

Even when restarting the app/phone it still crashes.

I'm not sure if its me or the dynamic-features screwing up here.

**Comment by TechaosAdam** [comment]
I’m not sure internally what is going wrong, the resources may have been downloaded and just can’t be found, or they weren’t downloaded at all.  I think it has more to do with the R.java file.  But if you put your resources in your main project, it should work, if you access them from your dynamically downloaded code.

**Comment by Stjinchan** [comment]
> I’m not sure internally what is going wrong, the resources may have been downloaded and just can’t be found, or they weren’t downloaded at all. I think it has more to do with the R.java file. But if you put your resources in your main project, it should work, if you access them from your dynamically downloaded code.

This is true, and I already found this as a working solution. But it beats the point of dynamic modules. Having only a .kt file while all the resources and layouts still in the base app beats the point of my app.

**Comment by TechaosAdam** [comment]
Same here. Dynamic delivery is clearly the future, and I waited till Google IO to use the feature because I expected they would make it open for people to use. But it doesn’t make much sense to use if basic things fail. What else is wrong with the feature, and imagine critical issues with complex use cases

**Comment by Stjinchan** [comment]
Let's assume this is a bug in dynamic-features and wait for a fix.
Let's hope we get a slightly more clear documentation on how to merge manifests for example.
And an option to uninstall right away instead of defer it.

**Comment by Stjinchan** [comment]
I disabled ondemand on my module, and it the module was successfully working. I called deferUninstall and waited for the module to be gone.

After reinstalling the module I get the resource not found exception.

**Comment by Baobomb** [comment]
> I disabled ondemand on my module, and it the module was successfully working. I called deferUninstall and waited for the module to be gone.
> 
> After reinstalling the module I get the resource not found exception.

Actually, disable onDemand on dynamic feature means user will download and install the dynamic module at first time installed from GP. 
It will not reduce the Apk size for user and also not the purpose what we want dynamic feature to reach.

I assume that SplitInstallManager do not attach the res from dynamic feature into main package after features downloaded.
For instance, after my dynamic features downloaded and installed,  I dump all id and name of resource after SplitInstallManager.updateAppInfo() for my Application context and there is not any resource from dynamic feature in the resource list at all.

Though dynamic feature is still in beta, I think what we can do is give google some time to fix it, 
or just put the resource in the base module at this moment as a work around :(

**Comment by TechaosAdam** [comment]
Yeah, I decided not to use the package at all right now. I don’t want to integrate these features until there is more clarity on how to build complex navigation and room dB integration. They stated at google IO that they were working on both. And given how the current bug seems so basic, I imagine they may make more breaking changes.... I’d rather wait until I’m confident that I can build complex apps with this design pattern without my code turning into spaghetti

**Comment by qichuan** [comment]
Did you remember to call `SplitCompat.install(this)` in `attachBaseContext()` method?

```

    @Override
    protected void attachBaseContext(Context newBase) {
        super.attachBaseContext(newBase);
        SplitCompat.install(this);
    }

```

According to the [doc](https://developer.android.com/reference/com/google/android/play/core/splitcompat/SplitCompat#install), it should be used in any activities inside dynamic feature modules.

**Comment by Stjinchan** [comment]
> Did you remember to call `SplitCompat.install(this)` in `attachBaseContext()` method?
> 
> ```
> 
>     @Override
>     protected void attachBaseContext(Context newBase) {
>         super.attachBaseContext(newBase);
>         SplitCompat.install(this);
>     }
> ```
> 
> According to the [doc](https://developer.android.com/reference/com/google/android/play/core/splitcompat/SplitCompat#install), it should be used in any activities inside dynamic feature modules.

Yes I (assume the others did too) did.

However my module has fragments instead of activities.
I can't seem to get this working

**Comment by Stjinchan** [comment]
After installing the module I get the following crash:

 `PID: 4932
    java.util.ConcurrentModificationException
        at java.util.HashMap$HashIterator.nextNode(HashMap.java:1441)
        at java.util.HashMap$KeyIterator.next(HashMap.java:1465)
        at com.google.android.play.core.listener.a.a(Unknown Source:13)
        at com.google.android.play.core.splitinstall.k.run(Unknown Source:12)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)`

**Comment by Baobomb** [comment]
> Did you remember to call `SplitCompat.install(this)` in `attachBaseContext()` method?
> 
> ```
> 
>     @Override
>     protected void attachBaseContext(Context newBase) {
>         super.attachBaseContext(newBase);
>         SplitCompat.install(this);
>     }
> ```
> 
> According to the [doc](https://developer.android.com/reference/com/google/android/play/core/splitcompat/SplitCompat#install), it should be used in any activities inside dynamic feature modules.

unfortunately, this is not work for this issue :(
As per what I comment at early, maybe the root cause is SplitCompat not working as we expected :(

**Comment by hansenji** [comment]
So I was experimenting and found that if you call `SplitCompat.install(this)` right after the feature is installed the resources are loaded. However, I don't know how stable this is.

**Comment by Baobomb** [comment]
Hey everyone who face with the same issue like me, I assume that I got solution.

I try to call SplitCompat.install every where before I access res in each Activity/Service or and.
Then use the context which have been SplitComtatInstall to getResource.
It's works!!

like following

```
public class MyActivity : Activity()/Service()/... {
    fun anyWhereWeStartInflateLayoutResource() {
        val splitCompatInstalledContext : Context = this;
        SplitCompat.install(splitCompatInstalledContext);
        LayoutInflator.from(splitCompatInstalledContext).inflate(.......)
        ...
        ...
    }
}
```

P.S : I also want to use GlobalContext which has been call with SplitCompat.install() in MyApplication's attachBaseContext for every where I want to access the resource in dynamic feature, but it is still not work, it only work for context from Activity/Service/Receiver.

**Comment by Stjinchan** [comment]
> Hey everyone who face with the same issue like me, I assume that I got solution.
> 
> I try to call SplitCompat.install every where before I access res.
> Then use the context which have been SplitComtatInstall to getResource.
> It's works!!
> 
> like following
> 
> ```
> public class MyActivity : Activity()/Service()/... {
>     fun anyWhereWeStartInflateLayoutResource() {
>         val splitCompatInstalledContext : Context = this
>         SplitCompat.install(splitCompatInstalledContext)
>         //Start load res
>         val stringRes = splitCompatInstalledContext.getString(id)
>         val drawableRes = splitCompatInstalledContext.getDrawable(id)
>         val colorRes = splitCompatInstalledContext.getColor(id)
>         LayoutInflator.from(splitCompatInstalledContext).inflate(.......)
>         ...
>         ...
>     }
> }
> ```
> 
> P.S : I also want to use GlobalContext which has been call with SplitCompat.install() in MyApplication's attachBaseContext for every where I want to access the resource in dynamic feature, but it is still not work, it only work for context from Activity/Service/Receiver.

Yes yes yes!
This is working fine for my fragments too.

Thanks! <3

**Comment by keyboardsurfer** [comment]
You don't have to call `SplitCompat.install` on every resource access, but should call it in any activity that is part of a dynamic-feature module.

**Comment by chaits98** [comment]
I know this issue is closed but I figured I should put this out there.
The answer by @qichuan is the correct one, though instead of doing this in any activities, override the attachBaseContext function in your Application class.

Don't forget to extend the application with SplitCompatApplication and adding the class name to manifest of your base module.

**Comment by igorescodro** [comment]
> You don't have to call `SplitCompat.install` on every resource access, but should call it in any activity that is part of a dynamic-feature module.

And when you are using it with Jetpack Navigation, I need to call it on the Dynamic Feature Fragment?

**Comment by Stjinchan** [comment]
What about classes that are in a dynamic feature module? How do I access resources from there?

**Comment by chaits98** [comment]
@Stjinchan you need to use reflection for that purpose
Use `Class.forName("com.yourpackage.YourClass").newInstance()`

In case you are using kotlin and need to reference an object file, use `Class.forName("com.yourpackage.YourClass").kotlin.objectInstance`

`newInstance()` method works for kotlin as well as Java class files.

**Comment by Stjinchan** [comment]
@chaits98 Is that how I can access resources from a non-activity class? Any way to get in contact with you outside of GitHub? I'm struggling with this case for a while now.

**Comment by chaits98** [comment]
Yes you can reach me at chaits98@gmail.com

**Comment by laalto** [comment]
I have been experimenting with dynamic feature modules and hit with this problem. Here's what I've found out so far in our setup:

 - String resources need to come from the base module
 - Other resources can come from the dynamic feature module

Could get the app bundle to work without these crashes and moving all resources to base by using `base.package.R` for strings and `feature.module.R` for other resources. It's fine for us since all our strings are already in base package for other tooling reasons. Kotlin's `import ... as` helps keep the code cleaner.

**Comment by Stjinchan** [comment]
@laalto String resources don't need to come from the base module. That would beat the point of dynamic feature modules.

**Comment by laalto** [comment]
@Stjinchan That was what I was believing at first but experiencing `java.lang.NoSuchFieldError: No static field` for string resource identifiers in the dynamic feature package `R` made me think otherwise, especially after resolving the crashes by changing string refs to an `R` in the base package. No minimal repro steps for a real bug report but anyway sharing my experience since googling for dynamic feature resource issues ended up here.

**Comment by Stjinchan** [comment]
@laalto all my layouts, strings and other values are in my dynamic feature module and works great. Did you Splitcompat.install?

**Comment by laalto** [comment]
Yes, both in base module application and dynamic feature activity.
