### ISSUE TITLE
dynamic feature of app bundle performs a very pool rate of success when downloading 

### ISSUE THREAD

**Issue by beyondckw** [googlesamples/android-dynamic-features#41]
Hi, i have any issues about app bundle, where or who i can looking for help? 
My application use app bundle for several days, including dynamic feature module. But dynamic feature  performs a very pool rate of success when downloading, about 25%. A lot of  error code are  FAILED and INTERNAL_ERROR, and i can not do something for this, because it is up to the downloading way of google . And then i search the docs but no help, "https://developer.android.com/guide/app-bundle/playcore#handle_request_errors". Please help me, or give me any suggestion, thanks.

**Comment by keyboardsurfer** [comment]
I recommend using the [Internal App Sharing](https://support.google.com/googleplay/android-developer/answer/9303479?hl=en) to test development of the on demand delivery code of your app.
