### ISSUE TITLE
Multi module compilation error: Dynamic features with dashed names

### ISSUE THREAD

**Issue by cesards** [googlesamples/android-dynamic-features#8]
I added a dynamic module to my multi-module project. Most of my modules contain dashes in their names and I haven't got any problems in compiling them, but when I add a dynamic feature model called "data-dropbox" I get the following error:
```
The following module names contain invalid characters. Names can only contain letters, digits and underscores.
	-> data-dropbox
```

Here is the structure of the project:

![screen shot 2018-05-29 at 8 47 35 am](https://user-images.githubusercontent.com/1536079/40659678-f91dbefc-631c-11e8-85b5-4a555f263f59.png)

I'm not sure if this is the right place to report the problem, since in the Issue Tracker there is no option to create a "tools/gradle" problem.

![screen shot 2018-05-29 at 8 45 17 am](https://user-images.githubusercontent.com/1536079/40659643-df9cf5ba-631c-11e8-9cf8-cb1a08862412.png)

I'm using AS 3.2 Canary 15 with Android Tools 28.0.0-rc1.

**Comment by keyboardsurfer** [comment]
For the time being, I recommend to use either underscores or camelCase as naming convention.

You can report this under https://issuetracker.google.com/issues/new?component=398856 and it'll get routed to the correct component.

**Comment by cesards** [comment]
Done. Thank you!

**Comment by kozaxinan** [comment]
https://issuetracker.google.com/issues/109923677
I expected they add the support for dash. Documentation still has examples with `dash`.   https://developer.android.com/studio/projects/dynamic-delivery

**Comment by keyboardsurfer** [comment]
Thanks for pointing out that the documentation needs updating here.
As it stands there's no support for `dash` in feature names.
The docs will be updated to reflect this shortly.

**Comment by nominalista** [comment]
Is it still planned to support modules with dashes? AS 3.4 allows only underscores.
